const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const WebSocket=require('ws');
class CDP {
 constructor(url){const u=new URL(url);if(u.protocol!=='ws:'||!['127.0.0.1','localhost'].includes(u.hostname))throw Error('Chrome phải chạy trên máy cục bộ');this.socket=new WebSocket(url,{handshakeTimeout:5000});this.pending=new Map();this.id=0;this.ready=new Promise((resolve,reject)=>{this.socket.once('open',resolve);this.socket.once('error',reject);});this.socket.on('error',()=>{});this.socket.on('message',raw=>{let msg;try{msg=JSON.parse(raw.toString());}catch{return;}const p=this.pending.get(msg.id);if(!p)return;clearTimeout(p.timer);this.pending.delete(msg.id);msg.error?p.reject(Error(msg.error.message)):p.resolve(msg.result);});this.socket.on('close',()=>{for(const p of this.pending.values()){clearTimeout(p.timer);p.reject(Error('Chrome đã đóng kết nối'));}this.pending.clear();});}
 async call(method,params={}){await this.ready;return new Promise((resolve,reject)=>{const id=++this.id,timer=setTimeout(()=>{this.pending.delete(id);reject(Error('Chrome không phản hồi: '+method));},10000);this.pending.set(id,{resolve,reject,timer});this.socket.send(JSON.stringify({id,method,params}),e=>{if(e){clearTimeout(timer);this.pending.delete(id);reject(e);}});});}
 async evaluate(expression){const r=await this.call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.text||'Không thao tác được trang');return r.result?.value;}
 close(){this.socket.close();}
}
function matchesProvider(url,provider){try{const u=new URL(url);return u.protocol==='https:'&&(provider==='chatgpt'?u.hostname==='chatgpt.com':['flow.google.com','flow.google'].includes(u.hostname)||u.hostname==='labs.google'&&u.pathname.startsWith('/fx/'));}catch{return false;}}
const promptLocator=`const visible=e=>e.getClientRects().length&&!e.disabled&&e.getAttribute('aria-disabled')!=='true';const items=[...document.querySelectorAll('textarea,[contenteditable="true"],[role="textbox"]')].filter(visible).filter(e=>![...e.querySelectorAll('textarea,[contenteditable="true"],[role="textbox"]')].some(visible));const ranked=items.map(e=>({e,score:/prompt|describe|mô tả|nhập|message|ask|tin nhắn|tạo|generate|imagine/i.test([e.getAttribute('placeholder'),e.getAttribute('aria-label'),e.getAttribute('data-placeholder')].join(' '))?4:1})).filter(x=>!/search|tìm kiếm/i.test([x.e.getAttribute('placeholder'),x.e.getAttribute('aria-label')].join(' '))).sort((a,b)=>b.score-a.score);`;
const detect=`(()=>{${promptLocator}if(!ranked.length)return {ready:false,note:'Đã kết nối Chrome nhưng chưa thấy ô prompt trong dự án'};if(ranked[1]?.score===ranked[0].score)return {ready:false,ambiguous:true,note:'Có nhiều ô nhập cùng mức ưu tiên; chưa xác định được ô prompt'};return {ready:true};})()`;
const openProjectExpression=`(()=>{const visible=e=>e.getClientRects().length&&!e.disabled&&e.getAttribute('aria-disabled')!=='true';const controls=[...document.querySelectorAll('button,[role="button"],a')].filter(visible),label=e=>(e.getAttribute('aria-label')||e.title||e.innerText||e.textContent||'').trim().replace(/^(?:add|plus) +/i,'').replace(/^[+ ]+/,'').trim(),matches=controls.filter(e=>/^(?:new project|create (?:a )?new project|start (?:a )?new project|dự án mới|tạo (?:dự án mới|dự án))$/i.test(label(e)));if(matches.length!==1)return {clicked:false,note:matches.length>1?'Có nhiều nút Dự án mới; không tự chọn nhầm':'Không tìm thấy nút Dự án mới. Trang có thể đang chờ đăng nhập hoặc chưa tải xong'};matches[0].click();return {clicked:true};})()`;
function configureExpression(job){
 const payload=JSON.stringify(job);
 return `(async()=>{
 const j=${payload},wait=ms=>new Promise(r=>setTimeout(r,ms));
 const visible=e=>e.getClientRects().length&&!e.disabled&&e.getAttribute('aria-disabled')!=='true';
 const text=e=>String(e.innerText||e.textContent||e.getAttribute('aria-label')||e.getAttribute('title')||'').trim();
 const norm=s=>String(s||'').toLocaleLowerCase().normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
 const controls=()=>[...document.querySelectorAll('button,[role="button"],[role="combobox"],[role="option"],[role="menuitem"],[role="radio"],[role="tab"]')].filter(visible);
 const modelKey=s=>{const n=norm(s).replace(/\\s/g,'');if(/veo.*31.*fast|veo.*3.*fast/.test(n))return'veo31fast';if(/veo.*31.*lite|veo.*3.*lite/.test(n))return'veo31lite';if(/veo.*31.*quality|veo.*3.*quality/.test(n))return'veo31quality';if(/(gemini)?omni.*flash/.test(n))return'geminiomniflash';if(/nano.*banana.*pro/.test(n))return'nanobananapro';if(/nano.*banana.*2/.test(n)||n==='nanobanana')return'nanobanana2';return n;};
 const match=(kind,wanted,value)=>{const n=norm(value),w=norm(wanted);if(kind==='model'){const a=modelKey(value),b=modelKey(wanted);return a===b||a.startsWith(b+' ');}if(kind==='ratio')return new RegExp('(?:^|\\\\D)'+String(wanted).replace(':','\\\\s*:\\\\s*')+'(?:\\\\D|$)').test(String(value));if(kind==='duration')return new RegExp('(?:^|\\\\D)'+String(wanted)+'\\\\s*(?:s|sec|seconds?|giay)?(?:\\\\D|$)','i').test(String(value));if(kind==='quality')return n===w||n.startsWith(w+' ');return false;};
 const selected=e=>e.getAttribute('aria-checked')==='true'||e.getAttribute('aria-selected')==='true'||e.getAttribute('aria-pressed')==='true'||e.getAttribute('data-state')==='checked'||e.classList?.contains('active')||e.classList?.contains('selected');
 async function chooseMode(){const wanted=j.kind==='video'?'video':'image',isMode=e=>{const n=norm(text(e));return wanted==='video'?/(^| )(video|videos)( |$)/.test(n):/(^| )(image|images|photo|photos)( |$)|hinh anh/.test(n);};let matches=controls().filter(isMode);if(matches.length===1){const e=matches[0];if(!selected(e))e.click();await wait(180);return {ok:true};}if(matches.length>1)return {ok:false,note:'Flow đang hiện nhiều lựa chọn loại '+wanted};const triggers=controls().filter(e=>/model|generation type|mode|mo hinh/.test(norm(e.getAttribute('aria-label')||''))||/veo|nano banana|omni flash/i.test(text(e)));if(triggers.length!==1)return {ok:false,note:'Không tìm thấy nút loại ảnh/video hoặc bộ chọn model trên Flow'};triggers[0].click();await wait(180);matches=controls().filter(isMode);if(matches.length!==1)return {ok:false,note:'Không tìm thấy lựa chọn '+(wanted==='video'?'Video':'Image')+' trong menu Flow'};matches[0].click();await wait(220);return {ok:true};}
 async function choose(kind,wanted){const all=controls(),label=s=>norm(s),isCurrent=e=>match(kind,wanted,text(e)),option=e=>['option','menuitem','radio'].includes(e.getAttribute('role'))||e.tagName==='BUTTON';
 let direct=all.filter(e=>option(e)&&isCurrent(e));if(direct.length===1){if(!selected(direct[0])){direct[0].click();await wait(180);}return {ok:true};}if(direct.length>1){const chosen=direct.filter(selected);if(chosen.length===1)return {ok:true};return {ok:false,note:'Flow đang hiện nhiều lựa chọn '+kind+' trùng nhau'};}
 let triggers=all.filter(e=>{const s=label(text(e)),a=label(e.getAttribute('aria-label')||'');if(kind==='model')return /model|mo hinh/.test(a)||/chon nhom mo hinh|veo|nano banana|omni/.test(s);if(kind==='ratio')return /aspect ratio|^ratio$|^ti le$/.test(a)||/^\d+\s*:?\s*\d+$/.test(s);if(kind==='duration')return /duration|thoi luong/.test(a)||/^\d{1,2}\s*(s|sec|seconds?|giay)?$/.test(s);if(kind==='quality')return /quality|resolution|chat luong/.test(a)||/^(360p|720p|1080p|1k|2k|4k)$/.test(s);return false;});
 const current=triggers.filter(isCurrent);if(current.length===1)return {ok:true};if(current.length>1)return {ok:false,note:'Có nhiều nút '+kind+' cùng hiển thị trên Flow'};
 if(kind==='model')triggers=triggers.filter(e=>/model|mo hinh/.test(label(e.getAttribute('aria-label')||''))||/chon nhom mo hinh|veo|nano banana|omni/.test(label(text(e))));
 if(triggers.length!==1)return {ok:false,note:'Không xác định duy nhất nút chọn '+kind+' trên Flow'+(triggers.length?': '+triggers.map(text).join(' | '):'')};
 triggers[0].click();await wait(180);
 const roleOpts=controls().filter(e=>['option','menuitem','radio'].includes(e.getAttribute('role'))&&match(kind,wanted,text(e)));
 const buttonOpts=controls().filter(e=>e!==triggers[0]&&(e.tagName==='BUTTON'||['button','option','menuitem','radio'].includes(e.getAttribute('role')))&&match(kind,wanted,text(e)));
 let opts=roleOpts.length?roleOpts:buttonOpts;
 if(opts.length!==1)return {ok:false,note:opts.length?'Flow đang hiện nhiều lựa chọn '+kind:'Flow chưa mở được danh sách '+kind};
 opts[0].click();await wait(180);
 const after=controls().filter(isCurrent);
 return after.length===1?{ok:true}:{ok:false,note:'Flow chưa xác nhận lựa chọn '+kind};
 }
 const required=[['mode',j.kind],['model',j.model],['ratio',j.ratio],...(j.kind==='video'?[['duration',j.duration]]:[]),...(j.kind==='video'?(j.quality||[]).slice(0,1).map(q=>['quality',q]):[])],results=[];
 for(const [kind,wanted] of required){const r=kind==='mode'?await chooseMode():await choose(kind,wanted);results.push({kind,wanted,...r});if(!r.ok)return {ok:false,results,note:r.note};}
 const count=controls().filter(e=>(['option','menuitem','radio'].includes(e.getAttribute('role'))||e.tagName==='BUTTON')&&/^x ?1$/.test(norm(text(e))));if(count.length===1&&!selected(count[0])){count[0].click();await wait(120);results.push({kind:'count',wanted:'x1',ok:true});}
 return {ok:true,results};
 })()`;
}
function prepareExpression(job){return `(()=>{const j=${JSON.stringify(job)};${promptLocator}if(!ranked.length||ranked[1]?.score===ranked[0].score)return {ok:false,note:'Không nhận diện duy nhất ô prompt. Kiểm tra dự án trên Chrome.'};const el=ranked[0].e;let text=j.provider==='chatgpt'?'Tạo ảnh với tỷ lệ '+j.ratio+'. '+j.prompt:j.prompt;el.focus();if(el.matches('textarea,input')){const proto=el.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(el,text);el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));}else if(el.isContentEditable){const r=document.createRange();r.selectNodeContents(el);const s=getSelection();s.removeAllRanges();s.addRange(r);document.execCommand('insertText',false,text);el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:text}));}else return {ok:false,note:'Ô prompt chưa hỗ trợ'};const inputs=[...document.querySelectorAll('input[type=file]')].filter(e=>!e.disabled),imageInputs=inputs.filter(e=>!/(video|audio)/i.test([e.accept,e.getAttribute('aria-label'),e.name].join(' '))&&(!e.accept||/image|\\.png|\\.jpe?g|\\.webp/i.test(e.accept))),uploads=[],mark=(input,images)=>{const id=crypto.randomUUID();input.setAttribute('data-hn-upload',id);uploads.push({selector:'[data-hn-upload="'+id+'"]',images});};let needsManual=false;const named=(list,re)=>list.filter(e=>re.test([e.getAttribute('aria-label'),e.title,e.name,e.accept].join(' ')));if(j.references?.length){const refs=named(imageInputs,/reference|ingredient|upload|image|anh/i),pool=refs.length?refs:imageInputs,multi=pool.filter(e=>e.multiple);const chosen=j.references.length>1?multi.length===1?multi[0]:null:pool.length===1?pool[0]:multi.length===1?multi[0]:null;if(chosen)mark(chosen,j.references);else needsManual=true;}const frames=[j.startImage,j.endImage].filter(Boolean);if(frames.length){const starts=named(imageInputs,/start|first|đầu/i),ends=named(imageInputs,/end|last|cuối/i);if(j.startImage&&starts.length===1)mark(starts[0],[j.startImage]);if(j.endImage&&ends.length===1)mark(ends[0],[j.endImage]);if(j.startImage&&starts.length!==1||j.endImage&&ends.length!==1){const multi=imageInputs.filter(e=>e.multiple);if(frames.length===2&&multi.length===1&&!uploads.length)mark(multi[0],frames);else needsManual=true;}}return {ok:true,uploads,needsManual};})()`;}
function submitExpression(job){return `(()=>{const j=${JSON.stringify(job)};if(j.seed)return {clicked:false,note:'Seed áp dụng thủ công; bỏ trống seed để tự bấm tạo'};const visible=e=>e.getClientRects().length&&!e.disabled&&e.getAttribute('aria-disabled')!=='true',label=e=>(e.getAttribute('aria-label')||e.title||e.innerText||e.textContent||'').trim(),buttons=[...document.querySelectorAll('button,[role="button"]')].filter(visible).filter(e=>/^(?:generate(?: image| video)?|create|send|send message|send prompt|tạo(?: ảnh| video)?|gửi)$/i.test(label(e)));if(!buttons.length){const localized=[...document.querySelectorAll('button,[role=button]')].filter(visible).filter(e=>/bắt đầu tạo/i.test(label(e)));if(localized.length===1)buttons.push(localized[0]);}if(buttons.length!==1)return {clicked:false,note:buttons.length?'Có nhiều nút tạo trên Flow; không tự bấm nhầm':'Không tìm thấy nút Bắt đầu tạo trên Flow'};buttons[0].click();return {clicked:true};})()`;}

const identityExpression=`(()=>{const visible=e=>e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden',nodes=[...document.querySelectorAll('span,div,p,button,a,[aria-label],[title]')].filter(visible),texts=nodes.map(e=>(e.innerText||e.textContent||'').trim()).filter(t=>t.length>0&&t.length<180),labels=nodes.map(e=>e.getAttribute('aria-label')||e.title||'').filter(Boolean),all=[...texts,...labels].join(' '),emails=[...new Set((all.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}/ig)||[]).map(x=>x.toLowerCase()))];return {email:emails.length===1?emails[0]:null,loggedIn:emails.length===1||!!document.querySelector('[contenteditable=\"true\"],textarea'),note:emails.length>1?'Flow hiện nhiều email; chỉ giữ một tab tài khoản':'Chưa thấy email đăng nhập'};})()`;
const accountExpression=`(()=>{const visible=e=>e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden',nodes=[...document.querySelectorAll('span,div,p,button,a,[aria-label],[title]')].filter(visible),texts=nodes.map(e=>(e.innerText||e.textContent||'').trim()).filter(t=>t.length>0&&t.length<140),values=[];for(const t of texts){const m=t.match(/^(?:(?:AI\\s+)?credits?(?:\\s+(?:remaining|left|available))?|tín dụng(?:\\s+google flow)?|điểm tín dụng)\\s*[:：]?\\s*([\\d,. ]+)$/i)||t.match(/^([\\d,. ]+)\\s*(?:(?:AI\\s+)?credits?(?:\\s+(?:remaining|left|available))?|tín dụng(?:\\s+google flow)?)$/i);if(m){const n=Number(m[1].replace(/[,. ]/g,''));if(Number.isSafeInteger(n)&&n>=0)values.push(n);}}const unique=[...new Set(values)],labels=nodes.map(e=>e.getAttribute('aria-label')||e.title||'').filter(Boolean),all=[...texts,...labels].join(' '),emails=[...new Set((all.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}/ig)||[]).map(x=>x.toLowerCase()))];return {credits:unique.length===1?unique[0]:null,email:emails.length===1?emails[0]:null,loggedIn:emails.length===1||!!document.querySelector('[contenteditable="true"],textarea'),note:unique.length>1?'Flow hiện nhiều số dư; không tự chọn nhầm':unique.length===1?'Đã đọc credits trực tiếp từ Flow':'Chưa thấy số credits; cần mở menu tài khoản Flow'};})()`;
const openAccountMenuExpression=`(()=>{const visible=e=>e.getClientRects().length&&!e.disabled,body=(document.body?.innerText||'').toLowerCase();if(/sign out|log out|đăng xuất/.test(body)&&/[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,}/i.test(body))return {opened:false,alreadyOpen:true};const candidates=[...document.querySelectorAll('button,[role="button"],[aria-label],[title]')].filter(visible).filter(e=>/google account|account menu|tài khoản google|manage your google account/i.test([e.getAttribute('aria-label'),e.title,e.innerText].filter(Boolean).join(' ')));if(candidates.length===1){candidates[0].setAttribute('data-hn-account-menu','open');candidates[0].click();return {opened:true};}return {opened:false,ambiguous:candidates.length>1};})()`;
const closeAccountMenuExpression=`(()=>{const e=document.querySelector('[data-hn-account-menu="open"]');if(!e)return {closed:false};e.click();e.removeAttribute('data-hn-account-menu');return {closed:true};})()`;
// Captures only UI labels and option state. Never reads input values, prompts,
// passwords, cookies, or account page text.
const recordUiExpression=`(()=>{const key='__hnFlowUiTrace';if(!window[key]){window[key]=[];const clean=s=>String(s||'').replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}/ig,'[email]').replace(/\\s+/g,' ').trim().slice(0,100);const add=(kind,e,extra={})=>{if(!e||e.closest('input[type=password],input[type=email],textarea,[contenteditable=\"true\"]'))return;const control=e.closest('button,[role="button"],[role="option"],[role="menuitem"],[role="tab"],[role="radio"],select,input[type=checkbox],input[type=radio],label,[role="combobox"]')||e;const label=clean(control.getAttribute('aria-label')||control.getAttribute('placeholder')||control.getAttribute('data-placeholder')||control.innerText||control.textContent);if(!label&&control.tagName!=='SELECT')return;window[key].push({kind,label:label||'select',tag:control.tagName.toLowerCase(),role:control.getAttribute('role')||'',...extra,at:new Date().toISOString()});if(window[key].length>1500)window[key].splice(0,window[key].length-1500);};document.addEventListener('click',e=>add('click',e.target),true);document.addEventListener('change',e=>{const t=e.target;if(t.matches('select')){const o=t.selectedOptions?.[0];add('select',t,{choice:clean(o?.textContent)});}else if(t.matches('input[type=checkbox],input[type=radio]'))add('toggle',t,{checked:!!t.checked});},true);}const events=window[key].splice(0,150);return events;})()`;
class ChromeDirect{
 constructor(store,dataDir){this.store=store;this.dataDir=dataDir;this.profiles=new Map();this.timer=setInterval(()=>this.tick(),3000);this.timer.unref();const used=new Set();for(const a of store.state.accounts){a.lastSeen=0;const dir=path.join(dataDir,'profiles',a.id);if(a.connectionMode==='direct'){let port=Number(a.debugPort)||9222;while(used.has(port))port++;used.add(port);this.watch(a,dir,port);}}}
 watch(a,profileDir,port=Number(a.debugPort)||9222){a.connectionMode='direct';a.debugPort=Number(port);const old=this.profiles.get(a.id);if(old){old.port=a.debugPort;old.started=Date.now();old.projectRequests=new Set();this.tick();return;}this.profiles.set(a.id,{a,profileDir,port:a.debugPort,session:crypto.randomUUID(),started:Date.now(),connections:new Map(),busy:false});this.status(a,'Đang kết nối Chrome qua cổng '+a.debugPort+'…');this.tick();}
 status(a,text){if(a.chromeStatus!==text){a.chromeStatus=text;this.store.log(a.name+': '+text,/chưa|không|nhiều ô/i.test(text)?'warn':'info',{accountId:a.id});this.store.save();}}
 startRecording(id){const p=this.profiles.get(id);if(!p)throw Error('Mở Chrome của tài khoản trước khi ghi thao tác');if(p.a.provider==='chatgpt')throw Error('Chế độ ghi hiện chỉ hỗ trợ Flow');p.recording=true;p.recordingEvents=[];this.store.log(p.a.name+': Bắt đầu ghi thao tác Flow (không lưu nội dung ô nhập).','info',{accountId:id});return {ok:true};}
 async stopRecording(id){const p=this.profiles.get(id);if(!p)throw Error('Không tìm thấy phiên Chrome để dừng ghi');if(p.busy){const deadline=Date.now()+5000;while(p.busy&&Date.now()<deadline)await new Promise(r=>setTimeout(r,50));}if(!p.busy){p.busy=true;try{await this.poll(p,{allowActions:false});}catch{}finally{p.busy=false;}}p.recording=false;const events=p.recordingEvents||[];p.recordingEvents=[];this.store.log(p.a.name+': Đã dừng ghi thao tác Flow ('+events.length+' sự kiện).','info',{accountId:id});return {ok:true,recordedAt:new Date().toISOString(),account:p.a.detectedEmail||p.a.name,events};}
 async tick(){await Promise.all([...this.profiles.values()].map(async p=>{if(p.busy)return;p.busy=true;try{await this.poll(p);}catch(e){p.a.lastSeen=0;p.a.chromeState='closed';const known=p.a.detectedEmail||p.a.loginObservedAt;const text=known?'Chrome đã đóng · vẫn lưu tài khoản và credits lần đọc gần nhất':'Chrome đã đóng hoặc mất kết nối';if(p.lastError!==e.message){p.lastError=e.message;this.store.log(p.a.name+': '+text,'warn',{accountId:p.a.id});this.store.save();}this.status(p.a,text);}finally{p.busy=false;}}));}
 async poll(p,{refreshCredits=false,allowActions=true}={}){let port=Number(p.port||p.a.debugPort);if(!Number.isInteger(port)||port<1||port>65535){try{port=Number(fs.readFileSync(path.join(p.profileDir,'DevToolsActivePort'),'utf8').split(/\r?\n/)[0]);}catch{port=0;}}if(!Number.isInteger(port)||port<1||port>65535)throw Error('Chrome chưa mở cổng DevTools '+(p.a.debugPort||9222));const response=await fetch(`http://127.0.0.1:${port}/json/list`,{signal:AbortSignal.timeout(5000)});if(!response.ok)throw Error('Chrome không phản hồi trên cổng '+port);const targets=(await response.json()).filter(t=>t.type==='page'&&matchesProvider(t.url,p.a.provider));for(const [id,c] of p.connections)if(!targets.some(t=>t.id===id)){c.close();p.connections.delete(id);}const candidates=[],observations=[],pages=[],creditTarget=refreshCredits?(targets.find(t=>/project/i.test(t.url||''))||targets[0]):null;for(const t of targets){let c=p.connections.get(t.id);if(!c){const u=new URL(t.webSocketDebuggerUrl);if(Number(u.port)!==port)throw Error('Cổng websocket khác hồ sơ');c=new CDP(t.webSocketDebuggerUrl);p.connections.set(t.id,c);}try{if(p.recording&&p.a.provider!=='chatgpt'){const events=await c.evaluate(recordUiExpression);if(Array.isArray(events)&&events.length){const safePath=(()=>{try{return new URL(t.url).pathname;}catch{return '/';}})();for(const event of events)p.recordingEvents.push({...event,page:safePath});if(p.recordingEvents.length>3000)p.recordingEvents.splice(0,p.recordingEvents.length-3000);}}if(p.a.provider!=='chatgpt'){const shouldReadCredits=refreshCredits&&creditTarget?.id===t.id;let observation=shouldReadCredits?await c.evaluate(accountExpression):await c.evaluate(identityExpression);if(shouldReadCredits&&observation?.credits==null&&!p.openedAccountMenus?.has(t.id)){const menu=await c.evaluate(openAccountMenuExpression);if(menu?.opened){p.openedAccountMenus??=new Set();p.openedAccountMenus.add(t.id);await new Promise(r=>setTimeout(r,250));observation=await c.evaluate(accountExpression);await c.evaluate(closeAccountMenuExpression);}}observations.push(observation);}const detection=await c.evaluate(detect);pages.push({id:t.id,c,detection});if(detection?.ready)candidates.push(c);}catch{c.close();p.connections.delete(t.id);}}
 const balances=refreshCredits?[...new Set(observations.map(o=>o?.credits).filter(v=>v!==null&&v!==undefined))]:[];const email=observations.map(o=>o?.email).find(Boolean);if(email){p.a.detectedEmail=email;p.a.loginObservedAt=new Date().toISOString();}if(observations.some(o=>o?.loggedIn))p.a.loginObservedAt??=new Date().toISOString();if(refreshCredits){if(balances.length===1){p.a.credits=balances[0];p.a.observedAt=new Date().toISOString();p.a.creditSource='Đọc credits khi bấm kiểm tra tất cả';p.a.creditNote='';if(!this.store.state.jobs.some(j=>j.accountId===p.a.id&&['assigned','prepared','submitted','review','uncertain'].includes(j.status)))p.a.reserved=0;}else p.a.creditNote=balances.length>1?'Nhiều tab có số dư khác nhau; chỉ giữ một tab Flow.':observations.find(o=>o?.note)?.note||'Chưa đọc được credits từ Flow';}
 if(candidates.length!==1){p.a.lastSeen=0;if(candidates.length>1){p.a.chromeState='ambiguous';this.status(p.a,'Đã kết nối · có nhiều tab có ô prompt. Chỉ giữ một tab dự án cho hồ sơ này.');return;}const hasActive=this.store.state.jobs.some(j=>j.accountId===p.a.id&&['assigned','prepared','submitted','review','uncertain'].includes(j.status));if(allowActions&&p.a.provider!=='chatgpt'&&pages.length===1&&!pages[0].detection?.ambiguous&&!hasActive){p.projectRequests??=new Set();if(!p.projectRequests.has(pages[0].id)){const opened=await pages[0].c.evaluate(openProjectExpression);if(opened?.clicked){p.projectRequests.add(pages[0].id);p.projectOpenedAt=Date.now();p.a.chromeState='opening-project';this.status(p.a,'Đã kết nối · đang tự mở Dự án mới trên Flow…');return;}}if(p.projectOpenedAt&&Date.now()-p.projectOpenedAt<20000){p.a.chromeState='opening-project';this.status(p.a,'Đã mở Dự án mới · đang chờ ô prompt tải xong…');return;}}
 p.a.chromeState=pages.some(x=>x.detection?.ambiguous)?'ambiguous':'no-prompt';this.status(p.a,!targets.length?'Chrome đã kết nối nhưng chưa có tab Flow/ChatGPT':pages.find(x=>x.detection?.note)?.detection.note||'Chrome đã kết nối nhưng chưa thấy ô prompt trong dự án');return;}
 p.a.chromeState='ready';p.a.browserConnectedAt=new Date().toISOString();
 p.a.lastSeen=Date.now();this.status(p.a,'Đã kết nối tự động · '+(p.a.provider==='chatgpt'?'ChatGPT':'Flow'));if(!allowActions){this.store.save();return;}const c=candidates[0],job=this.store.dispatch(p.a,p.session);if(!job)return;
 try{const configuration=job.provider==='chatgpt'?{ok:true}:await c.evaluate(configureExpression(job));const prepared=await c.evaluate(prepareExpression(job));if(!prepared?.ok){this.store.event(p.a,{jobId:job.id,status:'prepared',note:prepared?.note||'Mở đúng dự án và thao tác trên Flow'});return;}for(const upload of prepared.uploads||[]){const paths=[];for(const image of upload.images){if(!/^data:image\/(png|jpeg|webp);base64,/.test(image.data))throw Error('Ảnh tham chiếu không hợp lệ');const ext=image.type==='image/jpeg'?'jpg':image.type==='image/webp'?'webp':'png';const dir=path.join(this.dataDir,'upload-cache',job.id);fs.mkdirSync(dir,{recursive:true});const dest=path.join(dir,crypto.randomUUID()+'.'+ext);fs.writeFileSync(dest,Buffer.from(image.data.split(',')[1],'base64'));paths.push(dest);}const doc=await c.call('DOM.getDocument');const node=await c.call('DOM.querySelector',{nodeId:doc.root.nodeId,selector:upload.selector});if(!node.nodeId)throw Error('Không thấy ô tải ảnh trong Flow. Mở phần thêm ảnh rồi thử lại.');await c.call('DOM.setFileInputFiles',{nodeId:node.nodeId,files:paths});}
 const configNote=configuration?.ok?'Đã xác nhận lựa chọn model và cấu hình. ':'Chưa chọn được đủ model/cấu hình ('+(configuration?.note||configuration?.results?.filter(x=>!x.ok).map(x=>x.kind).join(', ')||'kiểm tra thủ công')+'). ';const uploadNote=prepared.needsManual?'Một số ảnh không khớp ô tải ảnh của Flow; kiểm tra ảnh tham chiếu trên trang.':prepared.uploads?.length?'Đã tải ảnh tham chiếu vào Flow.':'Không có ảnh tham chiếu.';this.store.event(p.a,{jobId:job.id,status:'prepared',note:configNote+'Đã điền prompt. '+uploadNote+(job.auto&&configuration?.ok&&!prepared.needsManual?'':' Chưa bấm Tạo; kiểm tra cấu hình trên Flow.')});if(job.auto&&configuration?.ok&&!prepared.needsManual){const sent=await c.evaluate(submitExpression(job));if(sent?.clicked)this.store.event(p.a,{jobId:job.id,status:'submitted',note:'Đã bấm Tạo qua Chrome. Chờ kết quả trên trang rồi tải và xác nhận trong tool.'});else{job.note=sent?.note||'Chưa xác minh được cấu hình; bấm Tạo trên Flow';this.store.save();}}
 }catch(e){const current=this.store.state.jobs.find(j=>j.id===job.id);if(current&&['assigned','prepared','submitted'].includes(current.status))this.store.event(p.a,{jobId:job.id,status:'error',note:e.message});}
 }
 async checkAllCredits(){const errors=[];let checked=0;for(const a of this.store.state.accounts){if((a.provider||'flow')==='chatgpt')continue;const p=this.profiles.get(a.id);if(!p){a.creditNote='Mở Chrome và đăng nhập trước khi kiểm tra';errors.push(a.name+': chưa mở Chrome');continue;}const deadline=Date.now()+10000;while(p.busy&&Date.now()<deadline)await new Promise(r=>setTimeout(r,50));if(p.busy){errors.push(a.name+': Chrome đang bận, thử lại');continue;}p.busy=true;const previousObserved=p.a.observedAt;try{await this.poll(p,{refreshCredits:true,allowActions:false});if(p.a.observedAt!==previousObserved)checked++;else errors.push(a.name+': '+(p.a.creditNote||'chưa đọc được credits'));}catch(e){a.creditNote=e.message;errors.push(a.name+': '+e.message);this.status(a,'Không đọc được credit: '+e.message);}}this.store.save();return {checked,errors};}
 close(){clearInterval(this.timer);for(const p of this.profiles.values())for(const c of p.connections.values())c.close();}
}
module.exports={CDP,ChromeDirect,matchesProvider,configureExpression,prepareExpression,submitExpression,detect,identityExpression,accountExpression,openAccountMenuExpression,closeAccountMenuExpression,openProjectExpression,recordUiExpression};
