const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');const {Store}=require('../core.cjs');const {plan,matchRefs}=require('../planner.cjs');
function fixture(){return new Store(path.join(fs.mkdtempSync(path.join(os.tmpdir(),'hn-flow-')),'state.json'));}
const base={kind:'video',model:'Veo 3.1 - Fast',duration:'8',prompts:'Scene 1\nScene 2',cost:20,delay:10,refmode:'text'};
test('keeps reservations after uncertainty and does not resend after restart',()=>{let s=fixture(),a=s.addAccount('A');s.balance(a,100,'manual');a.lastSeen=Date.now();s.enqueue(base);s.running=true;const j=s.dispatch(a,'tab1');assert.equal(a.reserved,20);assert.equal(s.dispatch(a,'tab2'),null);s.event(a,{jobId:j.id,status:'error',note:'lost connection'});assert.equal(a.enabled,false);assert.equal(a.reserved,20);s=new Store(s.file);s.running=true;assert.equal(s.dispatch(s.account(a.id),'tab3'),null);});
test('separates providers, checks known budget and persists real observed balance',()=>{const s=fixture(),a=s.addAccount('Flow'),b=s.addAccount('GPT','chatgpt');a.lastSeen=b.lastSeen=Date.now();s.enqueue(base);s.running=true;assert.equal(s.dispatch(a,'a'),null);assert.equal(s.dispatch(b,'b'),null);s.balance(a,40,'manual');const j=s.dispatch(a,'a');assert.ok(j);assert.equal(a.credits,40);assert.equal(s.available(a),20);assert.throws(()=>s.balance(a,30,'DOM'));s.resolve(j.id,true,20);s.balance(a,20,'DOM');assert.equal(a.reserved,0);assert.equal(a.credits,20);});
test('failure confirmation preserves unknown charges and enables explicit retry only',()=>{const s=fixture(),a=s.addAccount('A');s.balance(a,40,'manual');a.lastSeen=Date.now();s.enqueue(base);s.running=true;const j=s.dispatch(a,'a');s.resolve(j.id,false,null);assert.equal(a.reserved,20);assert.equal(j.status,'failed');});
test('paragraph prompts preserved as one job',()=>{const result=plan({...base,prompts:'First line\nsecond line\n\nNext scene',split:'paragraph'});assert.equal(result.length,2);assert.equal(result[0].prompts,'First line\nsecond line');});
test('all five pairing modes and exact matching work',()=>{const images=[1,2,3,4].map(n=>({name:n+'.png'}));assert.equal(plan({...base,prompts:'one',samePrompt:true,refmode:'frames',pairing:'chain',references:images}).length,3);assert.equal(plan({...base,prompts:'one',samePrompt:true,refmode:'frames',pairing:'pairs',references:images}).length,2);assert.equal(plan({...base,prompts:'one',samePrompt:true,refmode:'frames',pairing:'one-many',starts:[images[0]],ends:images.slice(1)}).length,3);assert.equal(plan({...base,prompts:'one',samePrompt:true,refmode:'frames',pairing:'many-one',starts:images.slice(1),ends:[images[0]]}).length,3);assert.equal(plan({...base,refmode:'frames',pairing:'default',starts:images.slice(0,2),ends:images.slice(2)}).length,2);const refs=[{name:'REF_CHR_DEAN.jpg'}];assert.equal(matchRefs('REF_CHR_DEAN_WEDDING',refs,'exact').length,0);assert.equal(matchRefs('REF_CHR_DEAN walks',refs,'exact').length,1);});
test('rejects unsupported combinations and excess reference slots',()=>{assert.throws(()=>plan({...base,model:'Gemini Omni Flash',ends:[{}],refmode:'frames'}));assert.throws(()=>plan({...base,model:'Veo 3.1 - Quality',tab:'ingredients'}));assert.throws(()=>plan({...base,duration:'10'}));assert.throws(()=>plan({...base,provider:'chatgpt',references:Array(6).fill({})}));});
test('dependency waits for actual saved last frame',()=>{const s=fixture(),a=s.addAccount('A');s.balance(a,100,'manual');a.lastSeen=Date.now();s.enqueue({...base,prompts:'first'});const first=s.state.jobs[0];s.enqueue({...base,prompts:'next',dependsOn:first.id});s.running=true;assert.equal(s.dispatch(a,'a').id,first.id);s.resolve(first.id,true,20);a.nextAt=0;assert.equal(s.dispatch(a,'a'),null);first.lastFrame={name:'last-frame.png',type:'image/png',data:'data:image/png;base64,abc'};assert.equal(s.dispatch(a,'a').startImage.name,'last-frame.png');});
test('account image/video flags restrict dispatch',()=>{const s=fixture(),a=s.addAccount('A');a.lastSeen=Date.now();s.balance(a,100,'manual');s.enqueue({...base,prompts:'scene'});s.running=true;a.allowVideo=false;assert.equal(s.dispatch(a,'a'),null);a.allowVideo=true;assert.ok(s.dispatch(a,'a'));});
test('Flow with unread credits cannot dispatch, while zero credits allow only the free Lite image path',()=>{const s=fixture(),a=s.addAccount('Flow');a.lastSeen=Date.now();s.enqueue({...base,kind:'image',cost:0,prompts:'portrait'});s.running=true;assert.equal(s.dispatch(a,'tab'),null);assert.equal(s.public().accounts[0].runtimeState,'unknown');s.balance(a,0,'Flow');const j=s.dispatch(a,'tab');assert.equal(j.model,'Nano Banana 2 Lite');assert.equal(j.cost,0);assert.equal(s.public().accounts[0].runtimeState,'low-credit');});
test('closed Chrome keeps the recognized account and last known balance visible',()=>{const s=fixture(),a=s.addAccount('Flow');a.detectedEmail='hoai@example.com';a.loginObservedAt=new Date().toISOString();a.credits=1250;a.observedAt=new Date().toISOString();a.lastSeen=0;const shown=s.public().accounts[0];assert.equal(shown.online,false);assert.equal(shown.sessionKnown,true);assert.equal(shown.runtimeState,'saved');assert.equal(shown.detectedEmail,'hoai@example.com');assert.equal(shown.credits,1250);});

test('tracks confirmed progress stages and flags a job interrupted after restart',()=>{let s=fixture(),a=s.addAccount('Flow');s.balance(a,40,'manual');a.lastSeen=Date.now();s.enqueue({...base,prompts:'one'});s.running=true;let j=s.dispatch(a,'tab');assert.equal(j.progress,10);s.event(a,{jobId:j.id,status:'prepared',note:'prompt filled'});assert.equal(j.progress,30);s.event(a,{jobId:j.id,status:'submitted',note:'submitted',mediaBaseline:{images:3,videos:0}});assert.equal(j.progress,45);assert.deepEqual(j.mediaBaseline,{images:3,videos:0});s=new Store(s.file);j=s.state.jobs[0];assert.ok(j.interruptedAt);assert.match(j.errorDetail,/gián đoạn/);});
test('pre-submit errors release reservation and can be retried',()=>{const s=fixture(),a=s.addAccount('Flow');s.balance(a,40,'manual');a.lastSeen=Date.now();s.enqueue({...base,prompts:'one'});s.running=true;const j=s.dispatch(a,'tab');s.failBeforeSubmit(a,j.id,'Không tìm thấy nút tạo');assert.equal(j.status,'failed');assert.equal(j.progressStage,'Lỗi trước khi gửi');assert.equal(j.errorDetail,'Không tìm thấy nút tạo');assert.equal(a.reserved,0);});
