const {randomUUID,randomBytes}=require('node:crypto');
const fs=require('node:fs');
const active=new Set(['assigned','prepared','submitted','review']);
function budgetPlan(account,job){
 const provider=job.provider||'flow',available=account.credits==null?null:Math.max(0,account.credits-(account.reserved||0));
 if(provider!=='flow')return job.cost===0||available!=null&&available>=job.cost?{model:job.model,cost:job.cost,duration:job.duration,quality:job.quality,note:''}:null;
 if(!Number.isSafeInteger(account.credits)||available==null)return null;
 if(available<10&&job.autoModel!==false){
  if(job.kind==='image')return {model:'Nano Banana 2 Lite',cost:0,duration:job.duration,quality:['1K'],note:'Tài khoản còn dưới 10 credits: tự chọn Nano Banana 2 Lite để tạo ảnh với mức dùng credits thấp nhất.'};
  if(available<=0)return null;
  const costs={4:4,6:5,8:6,10:7},requested=Number(job.duration)||8;
  const length=costs[requested]&&costs[requested]<=available?requested:Object.keys(costs).map(Number).filter(n=>costs[n]<=available).sort((a,b)=>b-a)[0];
  if(!length)return null;
  return {model:'Gemini Omni Flash 1.1',cost:costs[length],duration:String(length),quality:['360p'],note:`Tài khoản còn ${available} credits: tự chọn Gemini Omni Flash 360p, ${length}s (${costs[length]} credits).`};
 }
 return job.cost===0||available>=job.cost?{model:job.model,cost:job.cost,duration:job.duration,quality:job.quality,note:''}:null;
}
class Store{
 constructor(file){this.file=file;this.state={accounts:[],jobs:[],characters:[],logs:[],settings:{concurrency:1}};if(fs.existsSync(file))this.state=JSON.parse(fs.readFileSync(file,'utf8'));this.snapshotName=new Date().toISOString().replace(/[:.]/g,'-')+'.json';this.lastSnapshot=0;this.running=false;this.cursor=0;this.sessions=new Map();this.state.jobs.forEach(j=>{if(active.has(j.status)){j.interruptedAt=new Date().toISOString();j.errorDetail='Phiên trước bị gián đoạn. Cần kiểm tra Flow trước khi chạy tiếp để tránh tạo trùng.';j.note=j.errorDetail;}});}
 save(){fs.mkdirSync(require('node:path').dirname(this.file),{recursive:true});fs.writeFileSync(this.file+'.tmp',JSON.stringify(this.state,null,2),{mode:0o600});fs.renameSync(this.file+'.tmp',this.file);if(Date.now()-this.lastSnapshot>60000){const dir=require('node:path').join(require('node:path').dirname(this.file),'snapshots');fs.mkdirSync(dir,{recursive:true});fs.copyFileSync(this.file,require('node:path').join(dir,this.snapshotName));const files=fs.readdirSync(dir).filter(x=>x.endsWith('.json')).sort();for(const old of files.slice(0,-10))fs.unlinkSync(require('node:path').join(dir,old));this.lastSnapshot=Date.now();}}
 log(message,level="info",context={}){this.state.logs.unshift({time:new Date().toISOString(),message,level,...context});this.state.logs=this.state.logs.slice(0,300);}
 account(id){const a=this.state.accounts.find(a=>a.id===id);if(!a)throw Error('Không tìm thấy tài khoản');return a;}
 addAccount(name,provider="flow"){if(!String(name).trim())throw Error('Nhập tên tài khoản');const a={id:randomUUID(),name:String(name).trim().slice(0,120),provider,enabled:true,allowImage:true,allowVideo:true,credits:null,creditSource:'Chưa đọc',observedAt:null,reserved:0,key:randomBytes(32).toString('hex'),lastSeen:0};this.state.accounts.push(a);this.save();return a;}
 available(a){return a.credits==null?null:Math.max(0,a.credits-a.reserved);}
 public(){return {...this.state,running:this.running,accounts:this.state.accounts.map(({key,...a})=>{const online=Date.now()-a.lastSeen<15000,sessionKnown=!!(a.detectedEmail||a.loginObservedAt),runtimeState=!a.enabled?'disabled':a.credits==null?'unknown':a.credits<10?'low-credit':online?'ready':'saved';return {...a,online,sessionKnown,runtimeState,available:this.available(a)};})};}
 balance(a,value,source){if(!Number.isSafeInteger(value)||value<0)throw Error('Credits phải là số nguyên không âm');if(this.state.jobs.some(j=>j.accountId===a.id&&active.has(j.status)))throw Error('Chờ xác nhận tác vụ đang chạy trước khi cập nhật credits');a.credits=value;a.reserved=0;a.observedAt=new Date().toISOString();a.creditSource=source;this.save();}
 enqueue(data){const cost=Number(data.cost);if(!Number.isSafeInteger(cost)||cost<0)throw Error('Nhập mức credits dự kiến hợp lệ');if(!['image','video'].includes(data.kind))throw Error('Loại tác vụ không hợp lệ');const prompts=(data.singlePrompt?[String(data.prompts||'')]:String(data.prompts||'').split(/\r?\n/)).map(p=>p.trim()).filter(Boolean);if(!prompts.length)throw Error('Nhập ít nhất một prompt');if(prompts.length>500)throw Error('Tối đa 500 prompt mỗi lần');for(let prompt of prompts){for(const c of this.state.characters){prompt=prompt.replaceAll('@'+c.name,`[${c.name}: ${c.description}]`);}this.state.jobs.push({id:randomUUID(),prompt:prompt.slice(0,20000),kind:data.kind,model:String(data.model||'Theo cấu hình Flow').slice(0,100),ratio:data.ratio||'9:16',duration:String(data.duration||'8'),cost,auto:!!data.auto,autoModel:data.autoModel!==false,accountId:data.accountId||null,status:'queued',progress:0,progressStage:'Đang chờ',createdAt:new Date().toISOString(),note:'Chờ chạy',references:data.references||[],startImage:data.startImage||null,endImage:data.endImage||null,refmode:data.refmode||'text',tab:data.tab||'frames',quality:data.quality||['720p'],seed:data.seed||null,delay:Number(data.delay)||10,provider:data.provider||'flow',group:data.group||null,dependsOn:data.dependsOn||null,result:null});}this.save();}
 dispatch(a,session){a.lastSeen=Date.now();const old=this.state.jobs.find(j=>j.accountId===a.id&&active.has(j.status));if(old){if(old.status==='assigned'&&this.sessions.get(old.id)===session)return old;return null;}
 if(!this.running||!a.enabled||a.nextAt>Date.now())return null;if(this.state.jobs.filter(j=>active.has(j.status)).length>=this.state.settings.concurrency)return null;
 // Pick an account-specific model plan from the last manually checked balance.
 const eligible=this.state.accounts.filter(x=>x.enabled&&Date.now()-x.lastSeen<15000&&!this.state.jobs.some(j=>j.accountId===x.id&&active.has(j.status)));
 const j=this.state.jobs.find(j=>j.status==='queued'&&(!this.selected||this.selected.has(j.id))&&(!j.dependsOn||this.state.jobs.some(p=>p.id===j.dependsOn&&p.status==='done'&&p.lastFrame))&&(j.provider||'flow')===(a.provider||'flow')&&(!j.accountId||j.accountId===a.id)&&a[j.kind==='image'?'allowImage':'allowVideo']!==false&&budgetPlan(a,j));if(!j)return null;
 const choices=eligible.map(account=>({account,plan:(account.provider||'flow')===(j.provider||'flow')&&(!j.accountId||j.accountId===account.id)&&account[j.kind==='image'?'allowImage':'allowVideo']!==false?budgetPlan(account,j):null})).filter(x=>x.plan);const selected=choices[this.cursor%choices.length];if(selected&&selected.account.id!==a.id)return null;this.cursor++;
 if(selected){j.model=selected.plan.model;j.cost=selected.plan.cost;j.duration=selected.plan.duration;j.quality=selected.plan.quality||j.quality;j.budgetNote=selected.plan.note||'';}
 if(j.dependsOn){const prev=this.state.jobs.find(p=>p.id===j.dependsOn);if(j.kind==='image'){j.references=[prev.lastFrame];j.refmode='ingredients';}else{j.startImage=prev.lastFrame;j.refmode='frames';}}j.accountId=a.id;j.status='assigned';j.progress=10;j.progressStage='Đang kết nối Flow';j.errorDetail=null;j.interruptedAt=null;j.note=(j.budgetNote?j.budgetNote+' ':'')+'Đang đưa prompt sang Chrome';j.assignedAt=new Date().toISOString();j.startedAt=j.assignedAt;a.reserved+=j.cost;this.sessions.set(j.id,session);this.log(`Giao ${j.kind==='video'?'video':'ảnh'} cho ${a.name}${j.budgetNote?' · '+j.budgetNote:''}`);this.save();return j;}
 failBeforeSubmit(a,id,note){const j=this.state.jobs.find(j=>j.id===id&&j.accountId===a.id);if(!j||!['assigned','prepared'].includes(j.status))throw Error('Không thể đánh dấu lỗi trước khi gửi');a.reserved=Math.max(0,(a.reserved||0)-j.cost);this.running=false;this.selected=null;j.status='failed';j.progressStage='Lỗi trước khi gửi';j.errorDetail=String(note||'Flow chưa nhận prompt').slice(0,600);j.note=j.errorDetail;j.finishedAt=new Date().toISOString();this.log(j.errorDetail,'error',{jobId:j.id,accountId:a.id});this.save();return j;}
 event(a,data){const j=this.state.jobs.find(j=>j.id===data.jobId&&j.accountId===a.id);if(!j||!active.has(j.status))throw Error('Tác vụ không còn hoạt động');if(!['prepared','submitted','review','error'].includes(data.status))throw Error('Trạng thái không hợp lệ');const allowed={assigned:['prepared','submitted','error'],prepared:['submitted','review','error'],submitted:['review','error'],review:['review']};if(!allowed[j.status]?.includes(data.status))throw Error('Chuyển trạng thái không hợp lệ');j.status=data.status;j.note=String(data.note||'').slice(0,600);if(data.status==='prepared'){j.progress=Math.max(j.progress||0,30);j.progressStage='Đã cấu hình và điền prompt';}if(data.status==='submitted'){j.progress=Math.max(j.progress||0,45);j.progressStage='Flow đang tạo';j.submittedAt=new Date().toISOString();if(data.mediaBaseline)j.mediaBaseline=data.mediaBaseline;}if(data.status==='review'){j.progress=90;j.progressStage='Đã thấy kết quả trên Flow';}if(data.status==='error')j.errorDetail=String(data.note||'Lỗi không rõ').slice(0,600);if(data.result&&/^https:\/\//.test(data.result))j.result=data.result.slice(0,4000);if(data.status==='error'){j.status='uncertain';j.progressStage='Cần kiểm tra';j.errorDetail=j.note+' — kiểm tra Flow, không tự thử lại vì có thể đã tiêu credits.';j.note=j.errorDetail;a.enabled=false;}this.log(j.note,data.status==='error'?'error':'info',{jobId:j.id,accountId:a.id});this.save();}
 resolve(id,success,spent){const j=this.state.jobs.find(j=>j.id===id);if(!j||!['assigned','prepared','submitted','review','uncertain'].includes(j.status))throw Error('Chọn tác vụ cần xác nhận');const a=this.account(j.accountId);if(spent!==null&&spent!==undefined){spent=Number(spent);if(!Number.isSafeInteger(spent)||spent<0)throw Error('Credits đã dùng không hợp lệ');a.reserved=Math.max(0,a.reserved-j.cost)+spent;} // reservation is an estimate, not a claimed Google balance
 a.nextAt=Date.now()+1000*(j.delay||10);j.status=success?'done':'failed';j.progress=success?100:(j.progress||0);j.progressStage=success?'Hoàn tất':(j.errorDetail?'Thất bại':'Đã xác nhận thất bại');j.errorDetail=success?null:(j.errorDetail||'Đã xác nhận thất bại');j.note=success?'Đã xác nhận kết quả':j.errorDetail;j.finishedAt=new Date().toISOString();this.save();}
}
module.exports={Store,active,budgetPlan};
