const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),net=require('node:net');
const {Store,active,budgetPlan}=require('./core.cjs');
const UI_TOKEN=crypto.randomBytes(32).toString('hex');
const {configureExpression,prepareExpression,submitExpression,detect,accountExpression,openProjectExpression,openAccountMenuExpression,closeAccountMenuExpression}=require('./chrome-direct.cjs');
const EXTENSION_ID='mafaioocjnmcdnhfdakilbgoihlbebbe';
function createServer({dataDir=path.join(os.homedir(),'HNStudio-Flow-Controlled'),extensionDir=path.join(__dirname,'extension'),port=17842}={}){
 const store=new Store(path.join(dataDir,'workspace.json'));const direct=new (require('./chrome-direct.cjs').ChromeDirect)(store,dataDir);
 function portIsFree(port){return new Promise(resolve=>{const probe=net.createServer();probe.once('error',()=>resolve(false));probe.listen(port,'127.0.0.1',()=>probe.close(()=>resolve(true)));});}
 async function debugPortFor(a){const current=direct.profiles.get(a.id);if(current)return current.port;const used=new Set([...direct.profiles.values()].map(p=>p.port));let port=Number(a.debugPort)||9222;while(used.has(port)||!(await portIsFree(port)))port++;if(port>9299)throw Error('Không còn cổng Chrome DevTools trống trong dải 9222–9299');return port;}
 function accountCanRun(a,j){return !!budgetPlan(a,j);}
 function json(res,obj,status=200){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(obj));}
 async function body(req,maxBytes=32*1024*1024){let text='';for await(const b of req){text+=b;if(text.length>maxBytes)throw Error('Dữ liệu quá lớn');}return text?JSON.parse(text):{};}
 const server=http.createServer(async(req,res)=>{try{
 if(!/^(127\.0\.0\.1|localhost)(:\d+)?$/.test(req.headers.host||''))return json(res,{error:'Invalid host'},403);const url=new URL(req.url,'http://127.0.0.1'),origin=req.headers.origin||'';
 if(origin.startsWith('chrome-extension://')){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Access-Control-Allow-Headers','Authorization, Content-Type');res.setHeader('Access-Control-Allow-Methods','GET, POST, OPTIONS');}if(req.method==='OPTIONS'){res.writeHead(204);return res.end();}
 if(url.pathname.startsWith('/bridge/')){const key=(req.headers.authorization||'').replace(/^Bearer /,'');const a=store.state.accounts.find(a=>a.key===key);if(!a)return json(res,{error:'Mã kết nối không hợp lệ'},401);
 if(url.pathname==='/bridge/inspect'&&req.method==='GET')return json(res,{accountExpression,detectExpression:detect,openProjectExpression,openAccountMenuExpression,closeAccountMenuExpression});
 if(url.pathname==='/bridge/poll'&&a.connectionMode==='direct')return json(res,{job:null});
 if(url.pathname==='/bridge/poll'){const session=url.searchParams.get('session');if(!session||session.length>100)throw Error('Thiếu phiên');const job=store.dispatch(a,session);return json(res,{job,automation:job?{configure:configureExpression(job),prepare:prepareExpression(job),submit:submitExpression(job)}:null});}
 if(url.pathname==='/bridge/identity'&&req.method==='POST'){const d=await body(req);a.connectionMode='extension';a.lastSeen=Date.now();a.detectedEmail=typeof d.email==='string'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(d.email)?d.email.slice(0,200):a.detectedEmail||null;if(d.loggedIn)a.loginObservedAt??=new Date().toISOString();a.chromeState=d.loggedIn?'connected':'login-required';a.chromeStatus=d.loggedIn?'Extension đang kết nối Flow'+(a.detectedEmail?' · '+a.detectedEmail:''):'Chrome đã mở; cần đăng nhập Google thủ công';store.save();return json(res,{ok:true});}
 if(url.pathname==='/bridge/log'&&req.method==='POST'){const d=await body(req);const level=['info','warn','error'].includes(d.level)?d.level:'info';store.log(`${a.name}: ${String(d.message||'Extension hoạt động').slice(0,600)}`,level,{accountId:a.id,jobId:typeof d.jobId==='string'?d.jobId:undefined});a.lastSeen=Date.now();store.save();return json(res,{ok:true});}
 if(url.pathname==='/bridge/stage'&&req.method==='POST'){const d=await body(req,64*1024*1024),job=store.state.jobs.find(j=>j.id===d.jobId&&j.accountId===a.id&&j.status==='assigned');if(!job)throw Error('Tác vụ không còn được giao cho hồ sơ này');if(!Array.isArray(d.uploads)||d.uploads.length>10)throw Error('Danh sách ảnh tải lên không hợp lệ');const root=path.join(dataDir,'upload-cache',job.id);fs.mkdirSync(root,{recursive:true});let total=0;const uploads=[];for(const upload of d.uploads){if(typeof upload.selector!=='string'||!/^[\w\[\]="-]{1,160}$/.test(upload.selector)||!Array.isArray(upload.images)||upload.images.length<1||upload.images.length>10)throw Error('Thông tin ô tải ảnh không hợp lệ');const files=[];for(const image of upload.images){if(typeof image.data!=='string'||!/^data:image\/(png|jpeg|webp);base64,/.test(image.data))throw Error('Ảnh tham chiếu không hợp lệ');const bytes=Buffer.from(image.data.split(',')[1],'base64');total+=bytes.length;if(total>40*1024*1024)throw Error('Tổng ảnh tham chiếu vượt 40 MB');const ext=image.type==='image/jpeg'?'jpg':image.type==='image/webp'?'webp':'png';const dest=path.join(root,crypto.randomUUID()+'.'+ext);fs.writeFileSync(dest,bytes,{mode:0o600});files.push(dest);}uploads.push({selector:upload.selector,files});}return json(res,{uploads});}
 if(url.pathname==='/bridge/event'&&req.method==='POST'){store.event(a,await body(req));return json(res,{ok:true});}
 if(url.pathname==='/bridge/balance'&&req.method==='POST'){await body(req);return json(res,{ok:true,ignored:true,note:'Credits chỉ được cập nhật khi bấm kiểm tra tất cả tài khoản'});}return json(res,{error:'Not found'},404);}
 if(url.pathname.startsWith('/api/')){if(req.headers.authorization!=='Bearer '+UI_TOKEN)return json(res,{error:'Unauthorized'},401);
 if(url.pathname==='/api/state')return json(res,store.public());
 if(req.method!=='POST')return json(res,{error:'Method not allowed'},405);const d=await body(req);
 if(url.pathname==='/api/account/add')store.addAccount(d.name,d.provider==='chatgpt'?'chatgpt':'flow');
 else if(url.pathname==='/api/account/update'){const a=store.account(d.id);if(d.enabled!==undefined)a.enabled=!!d.enabled;for(const flag of ['allowImage','allowVideo'])if(d[flag]!==undefined)a[flag]=!!d[flag];if(d.credits!==undefined)store.balance(a,Number(d.credits),'Nhập tay từ Flow');}
 else if(url.pathname==='/api/accounts/check-credits'){const result=await direct.checkAllCredits();return json(res,result);}
 else if(url.pathname==='/api/account/delete'){const a=store.account(d.id);if(store.state.jobs.some(j=>j.accountId===a.id&&['assigned','prepared','submitted','review','uncertain'].includes(j.status)))throw Error('Xác nhận tác vụ đang xử lý trước khi xóa tài khoản');const profile=direct.profiles.get(a.id);if(profile){for(const c of profile.connections.values())c.close();direct.profiles.delete(a.id);}store.state.accounts=store.state.accounts.filter(x=>x.id!==a.id);store.log('Đã xóa hồ sơ khỏi danh sách: '+a.name);}
 else if(url.pathname==='/api/account/pair'){const a=store.account(d.id);return json(res,{code:JSON.stringify({endpoint:`http://127.0.0.1:${server.address().port}`,key:a.key}),extension:path.join(__dirname,'extension')});}
 else if(url.pathname==='/api/account/open'){
  const a=store.account(d.id),cp=require('node:child_process');
  const candidates=process.platform==='win32'?[path.join(process.env.PROGRAMFILES||'C:\\Program Files','Google/Chrome/Application/chrome.exe'),path.join(process.env['PROGRAMFILES(X86)']||'C:\\Program Files (x86)','Google/Chrome/Application/chrome.exe'),path.join(process.env.LOCALAPPDATA||'','Google/Chrome/Application/chrome.exe')]:process.platform==='darwin'?['/Applications/Google Chrome.app/Contents/MacOS/Google Chrome']:['/usr/bin/google-chrome','/usr/bin/chromium','/usr/bin/chromium-browser'];
  const exe=candidates.find(p=>fs.existsSync(p));if(!exe)throw Error('Cài Google Chrome trước khi mở tài khoản');
  const profileDir=path.join(dataDir,'profiles',a.id);fs.mkdirSync(profileDir,{recursive:true});
  const debugPort=await debugPortFor(a);a.debugPort=debugPort;direct.watch(a,profileDir,debugPort);
  const target=a.provider==='chatgpt'?'https://chatgpt.com/':'https://flow.google.com/';
  const args=['--user-data-dir='+profileDir,'--remote-debugging-address=127.0.0.1','--remote-debugging-port='+debugPort,'--remote-allow-origins=*','--no-first-run','--no-default-browser-check',target];
  const child=cp.spawn(exe,args,{detached:true,stdio:'ignore'});child.on('error',e=>store.log('Không mở được Chrome: '+e.message,'error',{accountId:a.id}));child.unref();
  a.chromeStatus='Đang mở Chrome riêng qua cổng '+debugPort+'…';a.chromeState='starting';store.log(a.name+': Mở Chrome riêng qua cổng DevTools '+debugPort+'.','info',{accountId:a.id});
 }
 else if(url.pathname==='/api/jobs/add'){const planned=require('./planner.cjs').plan(d);const group=crypto.randomUUID();let previous=null;for(const item of planned){store.enqueue({...item,singlePrompt:true,group,dependsOn:['storyboard','sequential'].includes(d.tab)?previous:null});previous=store.state.jobs.at(-1).id;}}
 else if(url.pathname==='/api/run'){if(d.running){const pending=store.state.jobs.filter(j=>j.status==='queued'&&(!d.selected||d.selected.includes(j.id)));if(!pending.length)throw Error('Không có tác vụ đang chờ được chọn để chạy');const ready=pending.some(j=>store.state.accounts.some(a=>a.enabled&&Date.now()-a.lastSeen<15000&&(a.provider||'flow')===(j.provider||'flow')&&(!j.accountId||j.accountId===a.id)&&a[j.kind==='image'?'allowImage':'allowVideo']!==false&&accountCanRun(a,j)));if(!ready)throw Error('Chưa sẵn sàng: mở Chrome, đăng nhập Flow, bấm Kiểm tra credit tất cả tài khoản, rồi xác nhận model/ảnh.');}store.running=!!d.running;store.log(d.running?'Bắt đầu chạy hàng chờ':'Đã tạm dừng giao tác vụ');store.selected=d.selected?new Set(d.selected):null;if(d.concurrency!==undefined){const n=Number(d.concurrency);if(!Number.isInteger(n)||n<1||n>5)throw Error('Số tài khoản chạy đồng thời: 1–5');store.state.settings.concurrency=n;}}
 else if(url.pathname==='/api/jobs/resolve')store.resolve(d.id,!!d.success,d.spent);
 else if(url.pathname==='/api/jobs/delete'){const j=store.state.jobs.find(j=>j.id===d.id);if(j&&['queued','done','failed'].includes(j.status))store.state.jobs=store.state.jobs.filter(j=>j.id!==d.id);else throw Error('Không xoá tác vụ đang xử lý');}
 else if(url.pathname==='/api/jobs/retry'){const j=store.state.jobs.find(j=>j.id===d.id);if(!j||j.status!=='failed')throw Error('Chỉ thử lại tác vụ đã xác nhận thất bại');store.state.jobs.push({...j,id:crypto.randomUUID(),status:'queued',result:null,note:'Chờ chạy lại',createdAt:new Date().toISOString()});}
 else if(url.pathname==='/api/result'){const j=store.state.jobs.find(j=>j.id===d.id);if(!j||!['prepared','submitted','review','uncertain'].includes(j.status))throw Error('Tác vụ không nhận kết quả');if(!/^(image\/(png|jpeg|webp)|video\/(mp4|webm))$/.test(d.type))throw Error('Chỉ nhận PNG, JPG, WebP, MP4 hoặc WebM');const ext=d.type.split('/')[1];const dest=path.join(dataDir,'output',j.id+'.'+ext);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,Buffer.from(d.base64,'base64'));j.localResult=dest;if(d.lastFrame&&['image/png','image/jpeg','image/webp'].includes(d.lastFrame.type)&&/^data:image\/(png|jpeg|webp);base64,/.test(d.lastFrame.data))j.lastFrame=d.lastFrame;j.status='review';j.note='Đã gắn file; xác nhận hoàn tất để chuyển hàng tiếp theo';}
 else if(url.pathname==='/api/character'){const name=String(d.name||'').trim();if(!/^[\p{L}\p{N}_-]{1,40}$/u.test(name))throw Error('Tên chỉ gồm chữ, số, _ hoặc -');if(store.state.characters.some(c=>c.name===name))throw Error('Tên nhân vật đã có');store.state.characters.push({id:crypto.randomUUID(),name,description:String(d.description||'').slice(0,4000)});}
 else if(url.pathname==='/api/character/delete')store.state.characters=store.state.characters.filter(c=>c.id!==d.id);
 else if(url.pathname==='/api/output/open'){const j=store.state.jobs.find(j=>j.id===d.id);if(!j?.localResult)throw Error('Chưa có file đã lưu');const folder=path.dirname(j.localResult);if(!folder.startsWith(path.resolve(dataDir)+path.sep))throw Error('Thư mục không hợp lệ');const cp=require('node:child_process');const exe=process.platform==='win32'?'explorer.exe':process.platform==='darwin'?'open':'xdg-open';const child=cp.spawn(exe,[folder],{stdio:'ignore'});child.on('error',e=>store.log(e.message));child.unref();}
 else if(url.pathname==='/api/jobs/edit'){const j=store.state.jobs.find(j=>j.id===d.id&&j.status==='queued');if(!j)throw Error('Chỉ sửa tác vụ chờ');if(d.prompt)j.prompt=String(d.prompt).slice(0,20000);if(d.startImage!==undefined)j.startImage=d.startImage;if(d.endImage!==undefined)j.endImage=d.endImage;if(d.references!==undefined)j.references=d.references;}
 else if(url.pathname==='/api/import-prompts'){const ext=String(d.ext).toLowerCase();if(!['xlsx','xls'].includes(ext))throw Error('Định dạng không hỗ trợ');const XLSX=require('./vendor/xlsx.cjs');const wb=XLSX.read(Buffer.from(d.base64,'base64'),{type:'buffer'});return json(res,{prompts:XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1}).map(r=>String(r[0]||'')).filter(Boolean).join('\n')});}
 else if(url.pathname==='/api/session/import'){if(!Array.isArray(d.jobs)||!Array.isArray(d.characters))throw Error('Phiên không hợp lệ');const ids=new Map(d.jobs.map(j=>[j.id,crypto.randomUUID()]));for(const j of d.jobs){if(!['image','video'].includes(j.kind)||typeof j.prompt!=='string')throw Error('Phiên có tác vụ không hợp lệ');store.enqueue({...j,singlePrompt:true,prompts:j.prompt,accountId:null,dependsOn:null});const added=store.state.jobs.at(-1);added.id=ids.get(j.id);added.dependsOn=ids.get(j.dependsOn)||null;added.status=j.status==='done'?'done':'queued';added.lastFrame=j.lastFrame;added.result=j.result;}store.state.characters=d.characters.filter(c=>typeof c.name==='string'&&typeof c.description==='string').map(c=>({...c,id:crypto.randomUUID()}));}
 else if(url.pathname==='/api/export')return json(res,{accounts:store.public().accounts,jobs:store.state.jobs,characters:store.state.characters});
 else return json(res,{error:'Not found'},404);store.save();return json(res,{ok:true});}
 const routes={'/':'index.html','/app.js':'app.js','/style.css':'style.css'};const f=routes[url.pathname];if(!f)return json(res,{error:'Not found'},404);let data=fs.readFileSync(path.join(__dirname,f));if(f==='index.html')data=Buffer.from(data.toString().replace('__TOKEN__',UI_TOKEN));res.writeHead(200,{'Content-Type':f.endsWith('.html')?'text/html; charset=utf-8':f.endsWith('.css')?'text/css':'application/javascript','Content-Security-Policy':"default-src 'self'; img-src 'self' data:; style-src 'self'; script-src 'self'; connect-src 'self'; media-src blob: 'self'; frame-ancestors 'none'",'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(data);
 }catch(e){store.log(e.message,'error',{route:req.url.split('?')[0]});store.save();json(res,{error:e.message},400);}});
 server.on('close',()=>direct.close());return {server,store,direct,start:()=>new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,'127.0.0.1',()=>resolve(`http://127.0.0.1:${server.address().port}`));})};
}
module.exports={createServer,EXTENSION_ID};if(require.main===module){const s=createServer();s.start().then(url=>console.log('HNStudio Flow AI: '+url)).catch(e=>{console.error('Không mở được ứng dụng: '+e.message);process.exitCode=1;});}
